[package]
name = "attestation"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
borsh = { workspace = true }
dcap-qvl = { workspace = true }
derive_more = { workspace = true }
dstack-sdk-types = { workspace = true }
hex = { workspace = true }
mpc-primitives = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
test_utils = { workspace = true }
