[package]
name = "mpc-devnet"
version = { workspace = true }
license = { workspace = true }
edition = "2021"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true }
clap = { workspace = true }
contract-interface = { workspace = true }
ed25519-dalek = { workspace = true }
flume = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
mpc-contract = { workspace = true, features = ["test-utils", "dev-utils"] }
near-account-id = { workspace = true }
near-sdk = { workspace = true }
node-types = { workspace = true }
# TODO(#658): use workspace version
rand = "0.9.0"
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
utilities = { workspace = true }

# TODO(#657): use workspace versions
near-crypto = "0.28.0"
near-jsonrpc-client = "0.15.1"
near-jsonrpc-primitives = "0.28.0"
near-primitives = "0.28.0"

[lints]
workspace = true
