[package]
name = "tee-launcher"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "tee-launcher"
path = "src/main.rs"

[features]
integration-test = []

[dependencies]
clap = { workspace = true }
dstack-sdk = { workspace = true }
hex = { workspace = true }
mpc-primitives = { workspace = true }
launcher-interface = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
