[package]
name = "test-parallel-contract"
version = { workspace = true }
license = { workspace = true }
edition = "2021"

[package.metadata.cargo-shear]
ignored = ["getrandom", "borsh", "serde"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
blstrs = { workspace = true }
borsh = { workspace = true }
contract-interface = { workspace = true }
elliptic-curve = { workspace = true }
hex = { workspace = true }
near-sdk = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }

# k256 won't compile without settings the custom rand flag for `getrandom`
[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.12", features = ["custom"] }
