[package]
name = "foreign-chain-inspector"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_more = { workspace = true }
http = { workspace = true }
jsonrpsee = { workspace = true }
mockall = { workspace = true }
mpc-primitives = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
httpmock = { workspace = true }
rstest = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
