[package]
name = "contract-interface"
version = "0.1.0"
edition = "2024"

[features]
abi = ["schemars"]

[dependencies]
borsh = { workspace = true }
bs58 = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
schemars = { workspace = true, optional = true }

[dev-dependencies]
near-sdk = { workspace = true }
serde_json = { workspace = true }
