[package]
name = "rpc-extractor"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http = { workspace = true }
mpc-primitives = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

[lints]
workspace = true
