[package]
name = "mpc-tls"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
ed25519-dalek = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
x509-parser = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
