[package]
name = "tee_authority"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
external-services-tests = []

[dependencies]
anyhow = { workspace = true }
backon = { workspace = true }
derive_more = { workspace = true }
dstack-sdk = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
mpc-attestation = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
hex = { workspace = true }
rstest = { workspace = true }
serde_json = { workspace = true }
test_utils = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }
