[package]
name = "chain-gateway"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
near-async = { workspace = true }
k256 = { workspace = true }
near-client = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
near-client-primitives = { workspace = true }
near-indexer = { workspace = true }
derive_more = {workspace=true}
near-indexer-primitives = { workspace = true }
ed25519-dalek = { workspace = true }
near-crypto = { workspace = true }
tracing = { workspace = true }
humantime = { workspace = true }
near-o11y = { workspace = true }
tracing-subscriber = { workspace = true }
near-account-id = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
