[package]
name = "utilities"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
near-account-id-v1 = { workspace = true }
near-account-id = { workspace = true }
