[package]
name = "near-mpc-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bounded-collections = { workspace = true }
contract-interface = { workspace = true }
derive_more = { workspace = true }
k256 = { workspace = true }
near-sdk = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }

[lints]
workspace = true
