[package]
name = "near-mpc-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bounded-collections = { workspace = true }
contract-interface = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
