[package]
name = "foreign-chain-rpc-interfaces"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_more = { workspace = true }
ethereum-types = { workspace = true }
jsonrpsee = { workspace = true }
mpc-primitives = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
