[package]
name = "mpc-attestation"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
attestation = { workspace = true }
borsh = { workspace = true }
mpc-primitives = { workspace = true }
serde = { workspace = true }
