[package]
name = "node-types"
version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = { workspace = true }
attestation = { workspace = true }
bs58 = { workspace = true }
ed25519-dalek = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
serde_json = { workspace = true }
