[package]
name = "dtos-contract"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bs58 = { workspace = true, optional = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
schemars = { workspace = true, optional = true }

[features]
abi = ["schemars"]
test-utils = ["bs58"]
