[package]
name = "include-measurements"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0"
attestation = { path = "../attestation" }
hex = "0.4"
proc-macro2 = "1.0"
quote = "1.0"
serde_json = "1.0"
syn = "2.0"

[dev-dependencies]
attestation = { path = "../attestation" }
hex = "0.4"
